language: python
python:
  - "2.7"
install: "make setup-ci"
script: "make tests"
sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df106e7590af361d5c02
    on_success: always
    on_failure: always
