web:
  image: hacklab/bikeanjo
  environment:
   - DJANGO_DEBUG=True
  ports:
   - "80:80"
  volumes:
   - .:/app
  links:
   - db:postgis
db:
  image: mdillon/postgis
  environment:
   - POSTGRES_PASSWORD=postgis
